name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_background: ^1.1.0
  flutter_svg: ^2.0.5
  google_fonts: ^6.0.0
  intl: ^0.18.1
  livekit_client: ^1.4.3
  logging: ^1.0.1
  permission_handler: ^11.0.0
  provider: ^6.0.1
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/logo-dark.svg
